jobs:
  docker_safe_build:
    executor: pcs/compute
    steps:
      - checkout
      - run: docker pull nginx
      - pcs/scan_image:
          prisma_cloud_compute_password: prisma_cloud_compute_password
          prisma_cloud_compute_url: https://us-east1.cloud.twistlock.com/us-1-111573457:8083
          prisma_cloud_compute_username: 9da38f4a-67ed-4d4d-8ce0-7cf929333f51
          prisma_cloud_scan_image: nginx
orbs:
  pcs: prisma_cloud/devops_security@3.0.0
version: 2.1
workflows:
  scan:
    jobs:
      - docker_safe_build
